backend:
  name: github
  repo: Linuslp/abdullohshavkatjonov # Make sure this matches your exact GitHub username/repo
  branch: main
  auth_type: implicit_assignment # Allows you to log in directly with GitHub

media_folder: "assets/uploads"

collections:
  - name: "blog"
    label: "Daily Blog"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
